CREATE DATABASE debezium;
USE debezium;
CREATE TABLE outbox (id SERIAL NOT NULL, aggregatetype VARCHAR(100) NOT NULL, aggregateid VARCHAR(100) NOT NULL, type VARCHAR(100) NOT NULL, payload JSON);
CREATE USER 'debezium'@'%' IDENTIFIED BY 'dbz';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES ON *.* TO 'debezium'@'%';
